# Ansible playbook to establish `nginx` web server and Emojis font.

---
- hosts: servers
  become: yes
  tasks:
    - name: Install `nginx`
      apt:
        name: nginx
        state: present

    - name: Remove `default` site from `sites-enabled`
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copy `nginx.conf` template to `sites-available` with name `my_webserv`
      template:
        src: ../src/nginx.conf
        dest: /etc/nginx/sites-available/my_webserv
      notify: restart_nginx

    - name: Create symlink `my_webserv` config to `sites-enabled`
      file:
        src: /etc/nginx/sites-available/my_webserv
        dest: /etc/nginx/sites-enabled/my_webserv
        state: link

    - name: Start `nginx` and enable auto launch after reboot
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: restart_nginx
      service:
        name: nginx
        state: restarted
