# Ansible playbook to establish `nginx` webserver and Emojis font.

---
- hosts: servers
  become: yes
  tasks:
    - name: Ensure `nginx`, `fonts-noto-color-emoji`, `openssl` are installed
      apt:
        name: ['nginx', 'fonts-noto-color-emoji', 'openssl']
        state: present

    - name: Check if `/etc/ssl/selfsigned_sert` directory exists
      stat:
        path: "/etc/ssl/selfsigned_sert"
      register: ssl_certificate_dir_exists_check

    - name: Create `/etc/ssl/selfsigned_sert` directory
      file:
        path: /etc/ssl/selfsigned_sert
        state: directory
        mode: 0775
        recurse: yes
      when: ssl_certificate_dir_exists_check is defined and
            ssl_certificate_dir_exists_check.stat.exists == false

    - name: Check ssl sertificate and private ley exists
      stat:
        path: "/etc/ssl/selfsigned_sert/{{item}}"
      with_items:
        - "sert.crt"
        - "privkey.pem"
      register: ssl_certificate_exists_check

    - name: Generate ssl selfsigned sertificate
      shell: "openssl req -newkey rsa:2048 -x509 -sha256 -days 30 -nodes \
              -out /etc/ssl/selfsigned_sert/sert.crt \
              -keyout /etc/ssl/selfsigned_sert/privkey.pem \
              -subj '/C=RU/ST=Tatarstan/L=Kazan/O=Andersen DevOps courses/\
              OU=Andrei Bulgakov/CN='"
      register: ssl_certificate_generated
      when: ssl_certificate_exists_check is defined and
            ssl_certificate_exists_check.results[0].stat.exists == false or
            ssl_certificate_exists_check.results[1].stat.exists == false

    - name: Remove `default` site from `sites-enabled`
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copy `nginx.conf` to `sites-available` with name `my_service`
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/my_service
      register: nginx_conf_copied

    - name: Create symlink `my_service` config to `sites-enabled`
      file:
        src: /etc/nginx/sites-available/my_service
        dest: /etc/nginx/sites-enabled/my_service
        state: link

    - name: Create `/var/www/my_service` directory for service files
      file:
        path: /var/www/my_service
        state: directory
        mode: 0775
        recurse: yes

    - name: Copy `index.html`
      copy:
        src: index.html
        dest: /var/www/my_service/

    - name: Ensure `nginx` is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Reload `nginx`
      service:
        name: nginx
        state: restarted
        enabled: yes
      when: nginx_conf_copied.changed or ssl_certificate_generated.changed
