# Ansible playbook for sequential launch of all playbooks in order.

---
- import_playbook: tasks/ssh_access.yml
- import_playbook: tasks/firewall.yml
- import_playbook: tasks/openssl.yml
- import_playbook: tasks/flask.yml
- import_playbook: tasks/nginx.yml
